export type Workspace = "general" | "coding";
export type MessagePart = { type: "text"; text: string };
export type ChatMessage = { id: string; role: "user" | "assistant"; parts: MessagePart[] };
export type Thread = { id: string; title: string; workspace: Workspace; projectId?: string; updatedAt: string; messages: ChatMessage[] };
export type Project = { id: string; name: string; description: string; status: string; stack: string; tone: string; tasks: { label: string; status: string; priority: string }[]; files: { name: string; type: string; status: string }[]; memory: string[]; decisions: string[]; changelog: string[] };

export const projects: Project[] = [
  { id: "gardens-zero", name: "Gardens Zero", description: "A quiet digital garden for essays, notes, and connected ideas.", status: "In progress", stack: "TanStack Start · TypeScript · Tailwind", tone: "Editorial, organic, precise", tasks: [{label:"Refine reading view",status:"In progress",priority:"High"},{label:"Map article relationships",status:"Next",priority:"Medium"},{label:"Content import",status:"Coming soon",priority:"Low"}], files: [{name:"product-brief.md",type:"Document",status:"Ready"},{name:"garden-map.png",type:"Image",status:"Reviewed"},{name:"reading-view.tsx",type:"Code",status:"Draft"}], memory:["Keep the reading experience calm and distraction-free.","Articles and content remain Coming soon until the publishing flow exists."], decisions:["Use a graph only as a secondary discovery tool.","Prioritize typography before social features."], changelog:["Mapped product structure","Drafted reading view","Added visual references"] },
  { id: "tend", name: "Tend", description: "A considered space for nurturing routines and personal systems.", status: "Coming soon", stack: "Not selected", tone: "Warm and restorative", tasks: [], files: [], memory:["Discovery has not started."], decisions:["Hold until Gardens Zero reaches a stable milestone."], changelog:["Project captured"] },
  { id: "exodus", name: "Exodus", description: "A private AI workspace for thoughtful digital product building.", status: "Active", stack: "TanStack Start · React · TypeScript", tone: "Calm, artistic, slightly dreamy", tasks: [{label:"Complete interaction prototype",status:"In progress",priority:"High"},{label:"Prepare data boundary",status:"Ready",priority:"High"},{label:"Connect real services",status:"Later",priority:"Low"}], files: [{name:"product-brief.md",type:"Document",status:"Ready"},{name:"Exodus.png",type:"Image",status:"Selected"},{name:"workspace-shell.tsx",type:"Code",status:"Active"}], memory:["Conversation stays at the visual center.","Use the logo’s turquoise and magenta sparingly.","Real connections come in a later phase."], decisions:["Use dedicated URLs for conversations.","Keep the first version local and replaceable."], changelog:["Approved product direction","Defined workspace architecture","Selected identity palette"] },
  { id: "portfolio", name: "Portfolio", description: "Selected product work, writing, and experiments.", status: "Planning", stack: "Astro · Content collections", tone: "Editorial and direct", tasks: [{label:"Select case studies",status:"Next",priority:"High"}], files:[{name:"case-study-outline.md",type:"Document",status:"Draft"}], memory:["Lead with outcomes, not process theatre."], decisions:["Keep navigation minimal."], changelog:["Created project outline"] },
  { id: "277-studios", name: "27/7 Studios", description: "Future studio work spanning products, tools, and collaborations.", status: "Exploring", stack: "To be recommended", tone: "Confident and experimental", tasks:[{label:"Define studio thesis",status:"Next",priority:"Medium"}], files:[], memory:["A home for future studio collaborations."], decisions:["Avoid premature service packaging."], changelog:["Captured initial direction"] },
];

export const initialThreads: Thread[] = [
 { id:"shape-exodus", title:"Shape the Exodus workspace", workspace:"general", projectId:"exodus", updatedAt:"Today", messages:[{id:"m1",role:"user",parts:[{type:"text",text:"I want Exodus to feel like a calm place to think and build, not another technical dashboard."}]},{id:"m2",role:"assistant",parts:[{type:"text",text:"That gives us a clear product principle: **conversation first, context nearby, complexity on demand.**\n\nA focused first pass could be:\n\n1. Make the conversation the largest visual surface.\n2. Keep projects and history in a quiet, collapsible rail.\n3. Reveal files, tasks, and memory only when they are useful.\n\n```ts\nconst principle = \"clarity before capability\";\n```\n\nWould you like to shape the project flow or the daily chat rhythm first?"}]}]},
 { id:"garden-reading", title:"Plan the Gardens Zero reading view", workspace:"coding", projectId:"gardens-zero", updatedAt:"Yesterday", messages:[{id:"m3",role:"user",parts:[{type:"text",text:"Plan a focused reading view for Gardens Zero. Keep it editorial and make related notes discoverable."}]},{id:"m4",role:"assistant",parts:[{type:"text",text:"Before I lock the structure, two questions: should related notes appear inline or after the article, and should the graph be visible by default?\n\n**Short implementation plan**\n- Establish a narrow reading column with generous margins.\n- Place related notes after the main text to preserve focus.\n- Keep the graph behind an intentional “Explore connections” action.\n- Add reading progress without making it feel like analytics."}]}]},
 { id:"studio-thesis", title:"Clarify the 27/7 Studios thesis", workspace:"general", projectId:"277-studios", updatedAt:"Sep 30", messages:[{id:"m5",role:"user",parts:[{type:"text",text:"Help me articulate what 27/7 Studios should become."}]},{id:"m6",role:"assistant",parts:[{type:"text",text:"Let’s separate the enduring idea from the services it may eventually offer. What kind of work should feel unmistakably at home under 27/7 Studios?"}]}]},
];

export const models = [
 { id:"kimi", name:"Kimi K2", capability:"Coding and reasoning", state:"Connected", preferred:true },
 { id:"general", name:"General model", capability:"General chat and planning", state:"Connected", preferred:false },
 { id:"vision", name:"Vision / image model", capability:"Image understanding and generation", state:"Disconnected", preferred:false },
 { id:"documents", name:"Document tools", capability:"PDF and document workflows", state:"Connected", preferred:false },
 { id:"voice", name:"Voice tools", capability:"Transcription and voice input", state:"Unavailable", preferred:false },
];

export const suggestions: Record<Workspace,string[]> = {
 general:["Research this idea","Plan a project","Review this document","Turn this into tasks","Help me think through a decision"],
 coding:["Start a new project","Understand this repository","Recommend a starting stack","Plan this feature","Generate a Python script","Explain this error"],
};
