import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
export function NewProjectDialog({open,onOpenChange,onCreated}:{open:boolean;onOpenChange:(v:boolean)=>void;onCreated:(name:string)=>void}){
 const [step,setStep]=useState(1); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [mode,setMode]=useState<"manual"|"recommend">("recommend"); const [type,setType]=useState("Web product"); const [stack,setStack]=useState("TanStack Start · TypeScript"); const [design,setDesign]=useState("Calm editorial"); const [repo,setRepo]=useState("New repository"); const [complexity,setComplexity]=useState("Focused"); const [saving,setSaving]=useState(false);
 const finish=()=>{setSaving(true);setTimeout(()=>{onCreated(name||"Untitled project");setSaving(false);setStep(1);setName("");onOpenChange(false)},700)};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><div className="mb-2 text-xs font-medium text-primary">New project · {step} of 3</div><DialogTitle>{step===1?"What are we making?":step===2?"Choose a starting point":"Review your project"}</DialogTitle><DialogDescription>{step===1?"Give Exodus enough context to shape a useful workspace.":step===2?"Choose directly or let Exodus recommend a sensible foundation.":"Nothing is connected yet. This creates a local prototype project."}</DialogDescription></DialogHeader>
 {step===1&&<div className="grid gap-4 py-2"><label className="grid gap-1.5 text-sm font-medium">Project name<Input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Field Notes"/></label><label className="grid gap-1.5 text-sm font-medium">Short description<Textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What should this become?"/></label><label className="grid gap-1.5 text-sm font-medium">Project type<Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Web product">Web product</SelectItem><SelectItem value="AI tool">AI tool</SelectItem><SelectItem value="Portfolio">Portfolio</SelectItem><SelectItem value="Academic work">Academic work</SelectItem></SelectContent></Select></label></div>}
 {step===2&&<div className="grid gap-4 py-2"><div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>setMode("manual")} className={`choice-tile ${mode==="manual"?"choice-tile-active":""}`}><span className="font-medium">Choose manually</span><span>Pick a known starting stack.</span></button><button type="button" onClick={()=>setMode("recommend")} className={`choice-tile ${mode==="recommend"?"choice-tile-active":""}`}><WandSparkles className="size-4"/><span className="font-medium">Recommend for me</span><span>Use the project description.</span></button></div><label className="grid gap-1.5 text-sm font-medium">Starting stack<Select value={stack} onValueChange={setStack}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TanStack Start · TypeScript">TanStack Start · TypeScript</SelectItem><SelectItem value="Next.js · TypeScript">Next.js · TypeScript</SelectItem><SelectItem value="Python · FastAPI">Python · FastAPI</SelectItem></SelectContent></Select></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-1.5 text-sm font-medium">Design direction<Select value={design} onValueChange={setDesign}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Calm editorial">Calm editorial</SelectItem><SelectItem value="Product minimal">Product minimal</SelectItem><SelectItem value="Expressive studio">Expressive studio</SelectItem></SelectContent></Select></label><label className="grid gap-1.5 text-sm font-medium">Complexity<Select value={complexity} onValueChange={setComplexity}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Focused">Focused</SelectItem><SelectItem value="Balanced">Balanced</SelectItem><SelectItem value="Ambitious">Ambitious</SelectItem></SelectContent></Select></label></div><label className="grid gap-1.5 text-sm font-medium">Repository status<Select value={repo} onValueChange={setRepo}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="New repository">New repository</SelectItem><SelectItem value="Existing repository">Existing repository</SelectItem><SelectItem value="No repository yet">No repository yet</SelectItem></SelectContent></Select></label></div>}
 {step===3&&<dl className="review-list"><div><dt>Name</dt><dd>{name||"Untitled project"}</dd></div><div><dt>Purpose</dt><dd>{description||"No description added"}</dd></div><div><dt>Type</dt><dd>{type}</dd></div><div><dt>Starting point</dt><dd>{mode==="recommend"?`Recommended · ${stack}`:stack}</dd></div><div><dt>Direction</dt><dd>{design} · {complexity}</dd></div><div><dt>Repository</dt><dd>{repo}</dd></div></dl>}
 <DialogFooter className="flex-row justify-between sm:justify-between"><Button variant="ghost" onClick={()=>step===1?onOpenChange(false):setStep(step-1)}>{step>1&&<ArrowLeft/>}{step===1?"Cancel":"Back"}</Button><Button disabled={step===1&&!name.trim()||saving} onClick={()=>step<3?setStep(step+1):finish()}>{saving?"Creating…":step===3?"Create project":"Continue"}{step<3?<ArrowRight/>:<Check/>}</Button></DialogFooter></DialogContent></Dialog>
}
